### PR TITLE
feat : Added song 

### PR DESCRIPTION
**Pull request by voidz7**

### CODE REVIEW

**Comment by voidz7** [comment]
There is a slight error in the steps for the git clone
image
ig it should be 
image
so fixed that typo in this pr

**Comment by bhargav794** [comment]
Thank you so much @voidz7  for fixing the readme error and also contributing to this fun little project your songs are added to [The_Coding_Playlist](https://open.spotify.com/playlist/042y1O3TdTdoVmmaiHnJxF?si=71c81582307e4a83)

**Comment by voidz7** [comment]
> Thank you so much @voidz7 for fixing the readme error and also contributing to this fun little project your songs are added to [The_Coding_Playlist](https://open.spotify.com/playlist/042y1O3TdTdoVmmaiHnJxF?si=71c81582307e4a83)

I would love to help maintain this project , and also would like to help working on the website for this project . So feel free to mention me 👍🏼

**Comment by bhargav794** [comment]
> I would love to help maintain this project, and also would like to help to work on the website for this project. So feel free to mention me 👍🏼

Thanks for your concern @voidz7 you will be the first person I will mention when I have started the website

**Pull request merged**
