### PR TITLE
Added a good song

### PR DESCRIPTION
**Pull request by SCHW18TZ**
Added Come and get your love which is one of the best song

### CODE REVIEW

**Comment by bhargav794** [comment]
Hey, @SCHW18TZ     Thank you so much for contributing to this fun little project  your song is added to [The_Coding_Playlist](https://open.spotify.com/playlist/042y1O3TdTdoVmmaiHnJxF?si=71c81582307e4a83). There are a total of 70 songs in the playlist now we also have other playlists you can check them out [here](https://github.com/bhargav794/hacktoberfest-practice-music-playlists/blob/main/playlists.md)

Thank you.

**Comment by bhargav794** [comment]
It really is one of the best songs

**Comment by SCHW18TZ** [comment]
it is btw will this count as a pr for the fest?

**Comment by bhargav794** [comment]
> it is btw will this count as a pr for the fest?

No, this repo is for practice purposes only that's I removed all the hacktoberfest tags and also mentioned the same Readme.md

**Pull request merged**
